Repository tipccjs/tipcc.js, pull requests merged in 2023-04, with the labels that each got.

#8 feat: Add max polling retries to client
  src/index.ts
  tsconfig.json
Labels: documentation, enhancement

#12 feat: Add documentation, adjust package.json (preparation for CI/CD), Replace local types by @tipccjs/tipcc-api-types
  .eslintrc.js
  .eslintrc.json
  .gitignore
  .prettierrc
  docs.css
  package-lock.json
  package.json
  src/index.ts
  src/structures/Amount.ts
  src/structures/CryptoCurrency.ts
  src/structures/CurrencyFormat.ts
  src/structures/CurrencyFormatUnits.ts
  src/structures/ExchangeRate.ts
  src/structures/FiatCurrency.ts
  src/structures/Transaction.ts
  src/structures/User.ts
  src/structures/Wallet.ts
  src/types/TipccApi.ts
  src/utils/CacheHandler.ts
  tsconfig.json
  typedoc.json
Labels: documentation, enhancement

#18 docs: Add categories, document properties
  src/index.ts
  src/structures/Amount.ts
  src/structures/Currency.ts
  src/structures/CurrencyCache.ts
  src/structures/CurrencyFormatting.ts
  src/structures/ExchangeRate.ts
  src/structures/RequestHandler.ts
  src/structures/TipccClient.ts
  src/structures/Transaction.ts
  src/structures/User.ts
  src/structures/Wallet.ts
  src/utils/Bucket.ts
  typedoc.json
Labels: documentation

#19 feat: Add option to format amount .toString() and value conversions for Amounts
  src/structures/Amount.ts
  src/structures/Currency.ts
  src/structures/CurrencyCache.ts
  src/structures/CurrencyFormatting.ts
  src/structures/ExchangeRate.ts
  src/structures/TipccClient.ts
  src/structures/Transaction.ts
  src/structures/Wallet.ts
  typedoc.json
Labels: enhancement

#31 fix: Remove unnecessary exports
  src/structures/managers/TransactionManager.ts
Labels: bug, documentation

#28 fix: Create transaction
  .gitignore
  src/structures/CurrencyCache.ts
  src/structures/RequestHandler.ts
  src/structures/managers/TransactionManager.ts
Labels: bug

#34 build: Prepare package for publishing
  .gitignore
  LICENSE
  package-lock.json
  package.json
  tsconfig.json
Labels: documentation, enhancement

#33 refactor: remove duplicate amounts, bug fixes
  src/structures/Amount.ts
  src/structures/RequestHandler.ts
  src/structures/Transaction.ts
  src/structures/Wallet.ts
  src/structures/managers/WalletManager.ts
Labels: bug
